import React, { createContext, useContext, useState, useEffect } from 'react';

export const translations = {
  en: {
    dir: 'ltr',
    nav: {
      about: 'About Us',
      services: 'Services',
      products: 'Products',
      contact: 'Contact',
      signIn: 'Sign In',
      dashboard: 'Dashboard',
      profile: 'Profile',
      servicesSocial: 'Social Media Growth',
      servicesAccounts: 'Premium Accounts',
      servicesSocialDesc: 'Boost your engagement',
      servicesAccountsDesc: 'Subscriptions & tools',
      socialEngagement: 'Social Engagement',
      entertainment: 'Entertainment',
      workTools: 'Work & AI Tools',
      instagram: 'Instagram',
      tiktok: 'TikTok',
      youtube: 'YouTube',
      facebook: 'Facebook',
      netflix: 'Netflix',
      spotify: 'Spotify',
      shahid: 'Shahid VIP',
      chatgpt: 'ChatGPT Plus',
      canva: 'Canva Pro',
      coursera: 'Coursera Plus',
    },
    toggle: {
      en: 'English',
      ar: 'العربية',
    },
    home: {
      heroTitle1: 'Speed',
      heroTitle2: 'Quality',
      heroAbout: 'Redefining the standards of digital growth in Jordan. Instant execution and seamless ',
      heroCliq: 'CliQ',
      heroAboutEnd: ' integration.',
      heroBtn: 'Explore Services',
      aboutLabel: 'About',
      categoriesAccounts: 'ACCOUNTS & SUBS',
      categoriesAccountsDesc: 'Accounts & Subscriptions',
      categoriesAccountsText1: 'Netflix, Steam, Spotify',
      categoriesAccountsText2: 'Premium Game Accounts',
      categoriesAccountsText3: 'Instant Delivery // 24-7',
      categoriesSocial: 'SOCIAL MEDIA',
      categoriesSocialDesc: 'Social Media Growth',
      categoriesSocialText1: 'Followers, Likes, Views',
      categoriesSocialText2: 'Real & Active Engagement',
      categoriesSocialText3: 'Global & Targeted // 2026',
      contactTitle: 'Contact Us',
      contactParagraph: 'We invite you to connect with us and explore how we can collaborate to achieve mutual digital success.',
      contactSocial: 'Social',
      contactPhone: 'Phone / WhatsApp',
      contactEmail: 'Email',
      contactSupport: 'Support Inquiries',
      contactApi: 'API Relations',
      contactBilling: 'CliQ Billing',
      contactLocations: 'Locations',
      contactAmman: 'Amman',
      contactAmmanValue: 'Amman, Jordan',
      contactGlobal: 'Global (Virtual)',
      contactGlobalValue1: 'Cloud Infrastructure Server',
      contactGlobalValue2: 'Node: 2026-US',
    },
    products: {
      hero1: 'Choose',
      hero2: 'Your',
      hero3: 'Service',
      pricingTitle: 'Social Media Pricing',
      pricingSub: 'Real engagement at the best prices in Jordan.',
      platforms: '4 Platforms',
      startingFrom: 'starting from',
      mostPopular: 'Most Popular',
      seePricing: 'See Pricing',
      jordanBadge: 'Jordanian Only',
      jordanTitleA: 'Jordanian',
      jordanTitleB: 'Service',
      jordanDesc: 'Pure Jordanian followers, likes & views. Real, active accounts from Jordan only.',
      jordanCheck1: '100% Real Jordanian Accounts',
      jordanCheck2: 'Starts within 1-5 minutes',
      jordanCheck3: '30-day Refill Guarantee',
      viewAllJordan: 'View All Jordanian Services',
      from: 'from',
      subsBadge: 'Subscriptions & Accounts',
      subsTitle: 'Premium Digital Subs',
      subsSub: 'Your favorite tools & streaming services for way less. Instant delivery, 24/7 support.',
      subsComingSoon: 'Coming Soon',
      subsComingSoonSub: 'Premium subscriptions & accounts are launching soon. Stay tuned for updates.',
      viewDetails: 'View Details',
      units: 'Units',
      elevate: 'Elevate your digital footprint. Start growing your audience instantly.',
      readyToBoost: 'Ready to boost your',
      growthQ: 'Growth for {name}?',
      getStarted: 'Get Started',
      trustCheck1Desc: 'We never ask for your password. All services are delivered safely via link or username.',
      trustCheck3Desc: 'Guaranteed refill for our premium services. We focus on high retention.',
      faqSafeQ: 'Is it safe for my accounts?',
      faqSafeA: 'Absolutely. We comply with platform limits, keeping your accounts 100% safe from bans.',
      faqDeliveryQ: 'How long does delivery take?',
      faqDeliveryA: 'Most social media orders start within 1-5 minutes. Subscriptions are delivered instantly.',
      faqPaymentQ: 'Can I pay using local methods?',
      faqPaymentA: 'Yes! We support instant local payments including CliQ, alongside standard cards.',
      faqRefillQ: 'What if my followers drop?',
      faqRefillA: 'Our premium packages include an automatic refill guarantee to ensure stability.',
      trustBadge: 'Built for Everyone',
      trustTitle: 'Your Privacy is our Priority.',
      trustPara: "You don't need to be a tech expert to use our platform. We designed MediaJo to be the safest and easiest way to boost your online presence without ever risking your accounts.",
      trustCheck1: 'No Passwords Required',
      trustCheck2: 'Pay instantly via CliQ or Cards',
      trustCheck3: 'Secure & Confidential Orders',
      createAccount: 'Create Free Account',
      orderCompleted: 'Order Completed',
      justNow: 'Just now',
      serviceLabel: 'Service',
      targetLabel: 'Target',
      trackOrder: 'Track Order',
      faqTitle: 'Got Questions?',
      faqSub: 'Everything you need to know about our consumer services.',
      processTitle: 'How It Works',
      step1Title: 'Choose Your Boost',
      step1Desc: 'Select from our wide range of social growth services or premium subscriptions.',
      step2Title: 'Provide Link',
      step2Desc: 'Just paste your profile or post link. We never ask for your passwords—ever.',
      step3Title: 'Watch It Grow',
      step3Desc: 'Pay securely via CliQ or card, and watch the results appear almost instantly.',
      svc: {
        'Arab Followers': 'Arab Followers',
        'Followers (No Warranty)': 'Followers (No Warranty)',
        'Likes (Reels/Posts)': 'Likes (Reels/Posts)',
        'Reels Views': 'Reels Views',
        'Followers (30-day)': 'Followers (30-day)',
        'Reels Likes': 'Reels Likes',
        'Subscribers': 'Subscribers',
        'Views': 'Views',
        'Likes': 'Likes',
        'Watch Hours': 'Watch Hours',
        'Jordanian Followers': 'Jordanian Followers',
        'Jordanian Likes': 'Jordanian Likes',
        'Jordanian Views': 'Jordanian Views',
        'Jordanian Comments': 'Jordanian Comments',
      },
      jordanDescMap: {
        'Real & active Jordanian accounts': 'Real & active Jordanian accounts',
        'From trusted Jordanian accounts': 'From trusted Jordanian accounts',
        'Views from Jordan only': 'Views from Jordan only',
        'Realistic Arabic & Jordanian comments': 'Realistic Arabic & Jordanian comments',
      },
      perMonth: '/month',
      cat: {
        'Entertainment': 'Entertainment',
        'Audio': 'Audio',
        'Streaming': 'Streaming',
        'AI Tools': 'AI Tools',
        'Design': 'Design',
        'Education': 'Education',
      },
    },
    platformPage: {
      home: 'Home',
      products: 'Products',
      socialMedia: 'Social Media',
      subtitle: 'Grow',
      subtitleTail: 'with real engagement at the best prices in Jordan.',
      orderNow: 'Order Now',
      added: 'Added',
      whyTitle: 'Why order from MediaJo?',
      feat1Title: 'No Passwords',
      feat1Text: 'We never ask for your passwords. Everything is done safely through links only.',
      feat2Title: 'Instant Delivery',
      feat2Text: 'Most orders start within 1 to 5 minutes of payment. Fast and reliable.',
      feat3Title: 'Local Payments',
      feat3Text: 'Pay instantly via CliQ or standard credit/debit cards.',
      notFound: 'Platform Not Found',
      backToProducts: 'Back to Products',
      premiumQuality: 'Premium Quality',
      trustSub: 'Engineered for safety, speed, and reliability.',
      hintMap: {
        'Arab followers': 'Arab followers',
        'Includes refill guarantee': 'Includes refill guarantee',
        'Best value': 'Best value',
        'Views on reels': 'Views on reels',
        'Likes on content': 'Likes on content',
        'Pure Jordanian accounts': 'Pure Jordanian accounts',
        'Views on videos': 'Views on videos',
        'Likes on reels': 'Likes on reels',
        '4K Ultra HD · 4 Devices': '4K Ultra HD · 4 Devices',
        'No Ads · Offline · High Quality': 'No Ads · Offline · High Quality',
        'Exclusive Shows · Live Sports': 'Exclusive Shows · Live Sports',
        'GPT-4 · DALL-E 3 · Priority Access': 'GPT-4 · DALL-E 3 · Priority Access',
        'Pro Templates · BG Remover · Brand Kit': 'Pro Templates · BG Remover · Brand Kit',
        'Unlimited Courses · Certificates': 'Unlimited Courses · Certificates',
      },
      svcType: {
        'likes': 'Likes',
        'views': 'Views',
        'followers': 'Followers',
        'subscribers': 'Subscribers',
      },
    },
    about: {
      discover: 'Discover',
      title1: 'Building the',
      title2: 'Digital Fabric',
      para: "Watch the abstract ideas materialize into real-world results. We construct the underlying architecture for your brand's growth, merging speed with uncompromising quality.",
      uptime: 'Uptime SLA',
      execution: 'Execution',
    },
    dashboard: {
      overview: 'Overview',
      myOrders: 'My Orders',
      cart: 'Cart',
      supportTickets: 'Support Tickets',
      profileSettings: 'Profile Settings',
      dashboardOverview: 'Dashboard Overview',
      menu: 'Menu',
      newOrder: 'New Order',

      systemOnline: 'System Online',
      welcomeBack: 'Welcome back, {name}!',
      readyBoost: 'Ready to boost your digital presence today?',
      walletBalance: 'Wallet Balance',
      recentOrders: 'Recent Orders',
      viewAll: 'View All',
      activeCart: 'Active Cart',
      cartWaiting: 'You have 1 item waiting in your cart.',
      cartWaitingPlural: 'You have {count} items waiting in your cart.',
      goToCheckout: 'Go to Checkout',
      support: 'Support',
      newReply: 'New reply on Ticket #441',
      replyPreview: '"Your Netflix account is ready..."',
      noNewMessages: 'No new messages. Need help with an order?',
      openSupport: 'Open Support',

      orderHistory: 'Order History',
      orderHistorySub: 'Track, manage, and review your purchases.',
      searchOrders: 'Search orders...',
      all: 'All',
      placedOn: 'Placed on ',
      viewDetails: 'View Details',
      noOrdersFound: 'No orders found',
      noOrdersWithStatus: 'You don\'t have any orders with the status "{filter}".',
      status: {
        completed: 'Completed',
        processing: 'Processing',
        canceled: 'Canceled',
      },

      yourCart: 'Your Cart',
      cartHeaderSub: 'Review your items before checkout.',
      itemSingle: 'Item',
      itemPlural: 'Items',
      cartEmpty: 'Your cart is empty',
      cartEmptySub: 'Looks like you haven\'t added any services yet.',
      orderSummary: 'Order Summary',
      promoCode: 'Promo code',
      apply: 'Apply',
      subtotal: 'Subtotal',
      serviceFee: 'Service Fee',
      total: 'Total',
      checkoutSecurely: 'Checkout Securely',
      sslEncrypted: 'SSL Encrypted Checkout',

      manageAccount: 'Manage your account details, security preferences, and contact info.',
      personalInfo: 'Personal Information',
      fullName: 'Full Name',
      emailAddress: 'Email Address',
      emailCannotChange: 'Email cannot be changed directly.',
      phoneWhatsapp: 'Phone Number / WhatsApp',
      saveChanges: 'Save Changes',
      profileUpdated: 'Profile updated successfully',
      profileUpdateFailed: 'Failed to update profile',
      securityPassword: 'Security & Password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      updatePassword: 'Update Password',
      passwordChanged: 'Password changed successfully',
      passwordChangeFailed: 'Wrong current password',

      fastAssistance: 'Get fast assistance from our 24/7 technical team.',
      openNewTicket: 'Open New Ticket',
      yourTickets: 'Your Tickets',
      selectTicket: 'Select a ticket',
      selectTicketSub: 'Choose a support ticket from the list to view the conversation details.',
      subject: 'Subject',
      subjectPlaceholder: 'e.g., Payment verification issue',
      message: 'Message',
      messagePlaceholder: 'Provide as much detail as possible...',
      submitTicket: 'Submit Ticket',
      typeReply: 'Type your reply...',
      describeIssue: 'Describe your issue and our team will respond shortly.',
      justNow: 'Just now',
      ticketStatus: {
        answered: 'Answered',
        open: 'Open',
        closed: 'Closed',
      },
      ticketCategory: {
        streaming: 'Streaming',
        socialMedia: 'Social Media',
        general: 'General',
      },
    },
    footer: {
      desc: 'Engineering digital growth infrastructure. Lightning-fast SMM arbitration built exclusively for the Jordanian market.',
      platform: 'Platform',
      company: 'Company',
      legal: 'Legal',
      platformLinks: ['Services', 'API Documentation', 'Pricing', 'Network Status'],
      companyLinks: ['About Us', 'Careers', 'Blog', 'Contact'],
      legalLinks: ['Terms of Service', 'Privacy Policy', 'Refund Policy'],
      rights: 'All rights reserved.',
      systemStatus: 'System Status:',
      operational: '100% Operational',
    },
    auth: {
      brand: 'MediaJo',
      welcome: 'Welcome',
      back: 'Back',
      sub: 'Sign in to manage your orders, track your growth, and unlock exclusive offers.',
      signInTitle: 'Sign In',
      signInSub: 'Access your MediaJo account',
      signInGoogle: 'Sign in with Google',
      signUpGoogle: 'Sign up with Google',
      or: 'or',
      email: 'Email',
      password: 'Password',
      forgot: 'Forgot?',
      signIn: 'Sign In',
      noAccount: "Don't have an account?",
      createOne: 'Create one',
      createTitle: 'Create Account',
      createSub: 'Join MediaJo and start growing',
      fullName: 'Full Name',
      yourName: 'Your name',
      confirmPassword: 'Confirm Password',
      createAccount: 'Create Account',
      haveAccount: 'Already have an account?',
      signOut: 'Sign Out',
      dashboardTitle: 'Dashboard',
      verifyTitle: 'Verify Your Email',
      verifySub: 'We sent a 6-digit verification code to',
      verifyCode: 'Verification Code',
      verifyButton: 'Verify & Continue',
      verifyHint: "Didn't receive the code?",
      resend: 'Resend Code',
      verifySuccess: 'Account created! Enter the code we sent to your email.',
      verifyError: 'Invalid or expired code. Please try again.',
      resendSuccess: 'A new code was sent to your email.',
      verifying: 'Verifying...',
      checkoutTitle: 'Login to Complete Your Order',
      checkoutSub: 'Your cart is saved on this device. Once you sign in, your items will be linked to your account.',
      checkoutUnverified: 'Your account is not verified yet. Verify your email to continue.',
      verifyNow: 'Verify Now',
    },
    contactPage: {
      contactUs: 'Contact Us',
      title: 'CONTACT',
      sub: 'Have a question or need support? Reach out through any of our channels and we will get back to you within 24 hours.',
      reachUs: 'Reach Us',
      emailTitle: 'Email',
      whatsappTitle: 'WhatsApp',
      phoneTitle: 'Phone',
      socialTitle: 'Social Media',
      support: 'Support',
      supportSub: 'We respond within minutes',
      infoLocations: 'Locations',
      infoGlobal: '+ Global virtual presence',
      infoResponse: 'Average response time',
      infoResponseSub: 'Under 5 minutes during business hours',
      sendTitle: 'Send a Message',
      sendSub: "Fill out the form and we'll be in touch.",
      phoneOptional: 'Phone (optional)',
      name: 'Full Name',
      namePlaceholder: 'Your name',
      email: 'Email',
      emailPlaceholder: 'you@example.com',
      subject: 'Subject',
      subjectPlaceholder: 'What is this about?',
      message: 'Message',
      messagePlaceholder: 'Write your message here...',
      send: 'Send Message',
      successTitle: 'Message Sent',
      successBody: 'Thank you! We will get back to you within 24 hours.',
      sendAnother: 'Send Another Message',
    },
  },
  ar: {
    dir: 'rtl',
    nav: {
      about: 'من نحن',
      services: 'الخدمات',
      products: 'المنتجات',
      contact: 'تواصل معنا',
      signIn: 'تسجيل الدخول',
      dashboard: 'لوحة التحكم',
      profile: 'الملف الشخصي',
      servicesSocial: 'نمو السوشال ميديا',
      servicesAccounts: 'حسابات مميزة',
      servicesSocialDesc: 'عزز تفاعلك',
      servicesAccountsDesc: 'اشتراكات وأدوات',
      socialEngagement: 'التفاعل الاجتماعي',
      entertainment: 'ترفيه',
      workTools: 'أدوات العمل والذكاء الاصطناعي',
      instagram: 'إنستغرام',
      tiktok: 'تيك توك',
      youtube: 'يوتيوب',
      facebook: 'فيسبوك',
      netflix: 'نتفليكس',
      spotify: 'سبوتيفاي',
      shahid: 'شاهد VIP',
      chatgpt: 'تشات جي بي تي',
      canva: 'كانفا برو',
      coursera: 'كورسيرا بلس',
    },
    toggle: {
      en: 'English',
      ar: 'العربية',
    },
    home: {
      heroTitle1: 'السرعة',
      heroTitle2: 'الجودة',
      heroAbout: 'نعيد تعريف معايير النمو الرقمي في الأردن. تنفيذ فوري وتكامل سلس مع ',
      heroCliq: 'كليك',
      heroAboutEnd: '.',
      heroBtn: 'استكشف الخدمات',
      aboutLabel: 'من نحن',
      categoriesAccounts: 'حسابات واشتراكات',
      categoriesAccountsDesc: 'Accounts & Subscriptions',
      categoriesAccountsText1: 'نتفليكس، ستيم، سبوتيفاي',
      categoriesAccountsText2: 'حسابات ألعاب مميزة',
      categoriesAccountsText3: 'توصيل فوري // 24-7',
      categoriesSocial: 'السوشال ميديا',
      categoriesSocialDesc: 'Social Media Growth',
      categoriesSocialText1: 'متابعون، لايكات، مشاهدات',
      categoriesSocialText2: 'تفاعل حقيقي ونشط',
      categoriesSocialText3: 'عالمي ومستهدف // 2026',
      contactTitle: 'تواصل معنا',
      contactParagraph: 'ندعوك للتواصل معنا واستكشاف كيف يمكننا التعاون لتحقيق نجاح رقمي متبادل.',
      contactSocial: 'اجتماعي',
      contactPhone: 'هاتف / واتساب',
      contactEmail: 'البريد الإلكتروني',
      contactSupport: 'استفسارات الدعم',
      contactApi: 'علاقات الـ API',
      contactBilling: 'فوترة كليك',
      contactLocations: 'المواقع',
      contactAmman: 'عمان',
      contactAmmanValue: 'عمان، الأردن',
      contactGlobal: 'عالمي (افتراضي)',
      contactGlobalValue1: 'خادم البنية التحتية السحابية',
      contactGlobalValue2: 'العقدة: 2026-US',
    },
    products: {
      hero1: 'اختر',
      hero2: 'خدمتك',
      hero3: 'المناسبة',
      pricingTitle: 'أسعار السوشال ميديا',
      pricingSub: 'تفاعل حقيقي بأفضل الأسعار في الأردن.',
      platforms: '4 منصات',
      startingFrom: 'تبدأ من',
      mostPopular: 'الأكثر طلباً',
      seePricing: 'عرض الأسعار',
      jordanBadge: 'أردني فقط',
      jordanTitleA: 'خدمة',
      jordanTitleB: 'أردنية',
      jordanDesc: 'متابعون وإعجابات ومشاهدات أردنية خالصة. حسابات حقيقية ونشطة من الأردن فقط.',
      jordanCheck1: 'حسابات أردنية حقيقية 100%',
      jordanCheck2: 'تبدأ خلال 1-5 دقائق',
      jordanCheck3: 'ضمان إعادة التعبئة 30 يوماً',
      viewAllJordan: 'عرض جميع الخدمات الأردنية',
      from: 'من',
      subsBadge: 'اشتراكات وحسابات',
      subsTitle: 'اشتراكات رقمية مميزة',
      subsSub: 'أدواتك وخدمات البث المفضلة بأسعار أقل بكثير. تسليم فوري ودعم على مدار الساعة.',
      subsComingSoon: 'قريباً',
      subsComingSoonSub: 'الاشتراكات والحسابات المميزة قادمة قريباً. ترقبوا التحديثات.',
      viewDetails: 'عرض التفاصيل',
      units: 'وحدة',
      elevate: 'ارتقِ ببصمتك الرقمية. ابدأ بتنمية جمهورك فوراً.',
      readyToBoost: 'هل أنت مستعد لتعزيز',
      growthQ: 'نمو {name}؟',
      getStarted: 'ابدأ الآن',
      trustCheck1Desc: 'لا نطلب كلمة مرورك أبداً. جميع الخدمات تُسلَّم بأمان عبر الرابط أو اسم المستخدم.',
      trustCheck3Desc: 'إعادة تعبئة مضمونة لخدماتنا المميزة. نركز على الاحتفاظ العالي بالمتابعين.',
      faqSafeQ: 'هل هو آمن لحساباتي؟',
      faqSafeA: 'بالتأكيد. نلتزم بحدود المنصات، مما يبقي حساباتك آمنة 100% من الحظر.',
      faqDeliveryQ: 'كم يستغرق التسليم؟',
      faqDeliveryA: 'تبدأ معظم طلبات السوشال ميديا خلال 1-5 دقائق. الاشتراكات تُسلَّم فوراً.',
      faqPaymentQ: 'هل يمكنني الدفع بطرق محلية؟',
      faqPaymentA: 'نعم! ندعم الدفع المحلي الفوري بما في ذلك CliQ، إضافة إلى البطاقات التقليدية.',
      faqRefillQ: 'ماذا لو انخفض متابعوني؟',
      faqRefillA: 'باقاتنا المميزة تشمل ضمان إعادة تعبئة تلقائي لضمان الاستقرار.',
      trustBadge: 'مصمم للجميع',
      trustTitle: 'خصوصيتك هي أولويتنا.',
      trustPara: 'لست بحاجة لأن تكون خبيراً تقنياً لاستخدام منصتنا. صممنا ميديا جو ليكون أسلم وأسهل طريقة لتعزيز حضورك الرقمي دون المخاطرة بحساباتك أبداً.',
      trustCheck1: 'لا حاجة لكلمات المرور',
      trustCheck2: 'ادفع فوراً عبر CliQ أو البطاقات',
      trustCheck3: 'طلبات آمنة وسرية',
      createAccount: 'إنشاء حساب مجاني',
      orderCompleted: 'اكتمل الطلب',
      justNow: 'الآن',
      serviceLabel: 'الخدمة',
      targetLabel: 'الهدف',
      trackOrder: 'تتبع الطلب',
      faqTitle: 'لديك أسئلة؟',
      faqSub: 'كل ما تحتاج معرفته عن خدماتنا.',
      processTitle: 'كيف تعمل الخدمة',
      step1Title: 'اختر خدمتك',
      step1Desc: 'اختر من مجموعتنا الواسعة لخدمات النمو أو الاشتراكات المميزة.',
      step2Title: 'أدخل الرابط',
      step2Desc: 'فقط ألصق رابط حسابك أو منشورك. لا نطلب كلمات المرور أبداً.',
      step3Title: 'شاهد النمو',
      step3Desc: 'ادفع بأمان عبر CliQ أو البطاقة وشاهد النتائج تظهر فوراً تقريباً.',
      svc: {
        'Arab Followers': 'متابعون عرب',
        'Followers (No Warranty)': 'متابعون (بدون ضمان)',
        'Likes (Reels/Posts)': 'إعجابات (ريلز/منشورات)',
        'Reels Views': 'مشاهدات ريلز',
        'Followers (30-day)': 'متابعون (30 يوماً)',
        'Reels Likes': 'إعجابات ريلز',
        'Subscribers': 'مشتركون',
        'Views': 'مشاهدات',
        'Likes': 'إعجابات',
        'Watch Hours': 'ساعات المشاهدة',
        'Jordanian Followers': 'متابعون أردنيون',
        'Jordanian Likes': 'إعجابات أردنية',
        'Jordanian Views': 'مشاهدات أردنية',
        'Jordanian Comments': 'تعليقات أردنية',
      },
      jordanDescMap: {
        'Real & active Jordanian accounts': 'حسابات أردنية حقيقية ونشطة',
        'From trusted Jordanian accounts': 'من حسابات أردنية موثوقة',
        'Views from Jordan only': 'مشاهدات من الأردن فقط',
        'Realistic Arabic & Jordanian comments': 'تعليقات عربية وأردنية واقعية',
      },
      perMonth: '/شهرياً',
      cat: {
        'Entertainment': 'ترفيه',
        'Audio': 'صوتيات',
        'Streaming': 'بث',
        'AI Tools': 'أدوات ذكاء اصطناعي',
        'Design': 'تصميم',
        'Education': 'تعليم',
      },
    },
    platformPage: {
      home: 'الرئيسية',
      products: 'المنتجات',
      socialMedia: 'السوشال ميديا',
      subtitle: 'نمِّ',
      subtitleTail: 'بتفاعل حقيقي وبأفضل الأسعار في الأردن.',
      orderNow: 'اطلب الآن',
      added: 'تمت الإضافة',
      whyTitle: 'لماذا تطلب من ميديا جو؟',
      feat1Title: 'بدون كلمات مرور',
      feat1Text: 'لا نطلب كلمات المرور أبداً. كل شيء يتم بأمان عبر الروابط فقط.',
      feat2Title: 'تسليم فوري',
      feat2Text: 'تبدأ معظم الطلبات خلال 1 إلى 5 دقائق من الدفع. سريع وموثوق.',
      feat3Title: 'مدفوعات محلية',
      feat3Text: 'ادفع فوراً عبر CliQ أو البطاقات الائتمانية/المدينة.',
      notFound: 'المنصة غير موجودة',
      backToProducts: 'العودة إلى المنتجات',
      premiumQuality: 'جودة متميزة',
      trustSub: 'مصممة للأمان والسرعة والموثوقية.',
      hintMap: {
        'Arab followers': 'متابعون عرب',
        'Includes refill guarantee': 'يشمل ضمان إعادة التعبئة',
        'Best value': 'أفضل قيمة',
        'Views on reels': 'مشاهدات على الريلز',
        'Likes on content': 'إعجابات على المحتوى',
        'Pure Jordanian accounts': 'حسابات أردنية خالصة',
        'Views on videos': 'مشاهدات على الفيديوهات',
        'Likes on reels': 'إعجابات على الريلز',
        '4K Ultra HD · 4 Devices': 'جودة 4K فائقة · 4 أجهزة',
        'No Ads · Offline · High Quality': 'بدون إعلانات · وضع آفل · جودة عالية',
        'Exclusive Shows · Live Sports': 'مسلسلات حصرية · رياضة مباشرة',
        'GPT-4 · DALL-E 3 · Priority Access': 'GPT-4 · دالي-3 · وصول مسبق',
        'Pro Templates · BG Remover · Brand Kit': 'قوالب احترافية · إزالة الخلفية · علامة تجارية',
        'Unlimited Courses · Certificates': 'دورات غير محدودة · شهادات',
      },
      svcType: {
        'likes': 'إعجابات',
        'views': 'مشاهدات',
        'followers': 'متابعون',
        'subscribers': 'مشتركون',
      },
    },
    about: {
      discover: 'اكتشف',
      title1: 'نبني',
      title2: 'البنية الرقمية',
      para: 'شاهد الأفكار المجردة تتحول إلى نتائج حقيقية. نبني البنية التحتية لنمو علامتك التجارية، ونجمع بين السرعة والجودة التي لا تقبل المساومة.',
      uptime: 'اتفاقية مستوى الخدمة',
      execution: 'التنفيذ',
    },
    dashboard: {
      overview: 'نظرة عامة',
      myOrders: 'طلباتي',
      cart: 'السلة',
      supportTickets: 'تذاكر الدعم',
      profileSettings: 'إعدادات الملف الشخصي',
      dashboardOverview: 'نظرة عامة على لوحة التحكم',
      menu: 'القائمة',
      newOrder: 'طلب جديد',

      systemOnline: 'النظام متصل',
      welcomeBack: 'أهلاً بعودتك، {name}!',
      readyBoost: 'هل أنت مستعد لتعزيز حضورك الرقمي اليوم؟',
      walletBalance: 'رصيد المحفظة',
      recentOrders: 'أحدث الطلبات',
      viewAll: 'عرض الكل',
      activeCart: 'السلة النشطة',
      cartWaiting: 'لديك عنصر واحد في انتظارك في السلة.',
      cartWaitingPlural: 'لديك {count} عناصر في انتظارك في السلة.',
      goToCheckout: 'الانتقال إلى الدفع',
      support: 'الدعم',
      newReply: 'رد جديد على التذكرة #441',
      replyPreview: '"حسابك في نتفليكس جاهز..."',
      noNewMessages: 'لا توجد رسائل جديدة. هل تحتاج مساعدة في طلب؟',
      openSupport: 'فتح الدعم',

      orderHistory: 'سجل الطلبات',
      orderHistorySub: 'تتبع طلباتك وإدارتها ومراجعتها.',
      searchOrders: 'ابحث في الطلبات...',
      all: 'الكل',
      placedOn: 'تم الطلب في ',
      viewDetails: 'عرض التفاصيل',
      noOrdersFound: 'لا توجد طلبات',
      noOrdersWithStatus: 'ليس لديك أي طلبات بحالة "{filter}".',
      status: {
        completed: 'مكتمل',
        processing: 'قيد التنفيذ',
        canceled: 'ملغى',
      },

      yourCart: 'سلة المشتريات',
      cartHeaderSub: 'راجع عناصرك قبل إتمام الطلب.',
      itemSingle: 'عنصر',
      itemPlural: 'عناصر',
      cartEmpty: 'سلتك فارغة',
      cartEmptySub: 'يبدو أنك لم تضف أي خدمات بعد.',
      orderSummary: 'ملخص الطلب',
      promoCode: 'رمز الخصم',
      apply: 'تطبيق',
      subtotal: 'المجموع الفرعي',
      serviceFee: 'رسوم الخدمة',
      total: 'الإجمالي',
      checkoutSecurely: 'إتمام الدفع بأمان',
      sslEncrypted: 'دفع مشفر عبر SSL',

      manageAccount: 'إدارة بيانات حسابك وتفضيلات الأمان ومعلومات الاتصال.',
      personalInfo: 'المعلومات الشخصية',
      fullName: 'الاسم الكامل',
      emailAddress: 'البريد الإلكتروني',
      emailCannotChange: 'لا يمكن تغيير البريد الإلكتروني مباشرة.',
      phoneWhatsapp: 'رقم الهاتف / واتساب',
      saveChanges: 'حفظ التغييرات',
      profileUpdated: 'تم تحديث البيانات الشخصية بنجاح',
      profileUpdateFailed: 'تعذر تحديث البيانات',
      securityPassword: 'الأمان وكلمة المرور',
      currentPassword: 'كلمة المرور الحالية',
      newPassword: 'كلمة المرور الجديدة',
      updatePassword: 'تحديث كلمة المرور',
      passwordChanged: 'تم تغيير كلمة المرور بنجاح',
      passwordChangeFailed: 'كلمة المرور الحالية غير صحيحة',

      fastAssistance: 'احصل على مساعدة سريعة من فريقنا الفني على مدار الساعة.',
      openNewTicket: 'فتح تذكرة جديدة',
      yourTickets: 'تذاكرك',
      selectTicket: 'اختر تذكرة',
      selectTicketSub: 'اختر تذكرة دعم من القائمة لعرض تفاصيل المحادثة.',
      subject: 'الموضوع',
      subjectPlaceholder: 'مثال: مشكلة في التحقق من الدفع',
      message: 'الرسالة',
      messagePlaceholder: 'قدم أكبر قدر ممكن من التفاصيل...',
      submitTicket: 'إرسال التذكرة',
      typeReply: 'اكتب ردك...',
      describeIssue: 'صِف مشكلتك وسيستجيب فريقنا قريباً.',
      justNow: 'الآن',
      ticketStatus: {
        answered: 'تمت الإجابة',
        open: 'مفتوحة',
        closed: 'مغلقة',
      },
      ticketCategory: {
        streaming: 'بث',
        socialMedia: 'سوشال ميديا',
        general: 'عام',
      },
    },
    footer: {
      desc: 'هندسة البنية التحتية للنمو الرقمي. تحكيم سريع لخدمات السوشال ميديا مصمم حصرياً للسوق الأردني.',
      platform: 'المنصة',
      company: 'الشركة',
      legal: 'قانوني',
      platformLinks: ['الخدمات', 'توثيق الـ API', 'الأسعار', 'حالة الشبكة'],
      companyLinks: ['من نحن', 'الوظائف', 'المدونة', 'تواصل معنا'],
      legalLinks: ['شروط الخدمة', 'سياسة الخصوصية', 'سياسة الاسترداد'],
      rights: 'جميع الحقوق محفوظة.',
      systemStatus: 'حالة النظام:',
      operational: 'يعمل بنسبة 100%',
    },
    auth: {
      brand: 'ميديا جو',
      welcome: 'أهلاً',
      back: 'بعودتك',
      sub: 'سجّل الدخول لإدارة طلباتك وتتبع نموك والوصول إلى عروض حصرية.',
      signInTitle: 'تسجيل الدخول',
      signInSub: 'الوصول إلى حساب ميديا جو',
      signInGoogle: 'الدخول عبر Google',
      signUpGoogle: 'التسجيل عبر Google',
      or: 'أو',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      forgot: 'نسيت؟',
      signIn: 'تسجيل الدخول',
      noAccount: 'ليس لديك حساب؟',
      createOne: 'أنشئ حساباً',
      createTitle: 'إنشاء حساب',
      createSub: 'انضم إلى ميديا جو وابدأ النمو',
      fullName: 'الاسم الكامل',
      yourName: 'اسمك',
      confirmPassword: 'تأكيد كلمة المرور',
      createAccount: 'إنشاء حساب',
      haveAccount: 'لديك حساب بالفعل؟',
      signOut: 'تسجيل الخروج',
      dashboardTitle: 'لوحة التحكم',
      verifyTitle: 'تحقق من بريدك الإلكتروني',
      verifySub: 'أرسلنا رمز تحقق من 6 أرقام إلى',
      verifyCode: 'رمز التحقق',
      verifyButton: 'تحقق والمتابعة',
      verifyHint: 'لم يصلك الرمز؟',
      resend: 'إعادة إرسال الرمز',
      verifySuccess: 'تم إنشاء الحساب! أدخل الرمز الذي أرسلناه إلى بريدك.',
      verifyError: 'الرمز غير صحيح أو منتهي الصلاحية. حاول مجدداً.',
      resendSuccess: 'تم إرسال رمز جديد إلى بريدك.',
      verifying: 'جاري التحقق...',
      checkoutTitle: 'سجّل الدخول لإتمام طلبك',
      checkoutSub: 'سلتك محفوظة على هذا الجهاز. بمجرد تسجيل الدخول ستُربط عناصرك بحسابك.',
      checkoutUnverified: 'حسابك غير مفعل بعد. تحقق من بريدك الإلكتروني للمتابعة.',
      verifyNow: 'تحقق الآن',
    },
    contactPage: {
      contactUs: 'تواصل معنا',
      title: 'تواصل',
      sub: 'لديك سؤال أو تحتاج دعماً؟ تواصل معنا عبر أي من قنواتنا وسنرد عليك خلال 24 ساعة.',
      reachUs: 'تواصل معنا',
      emailTitle: 'البريد الإلكتروني',
      whatsappTitle: 'واتساب',
      phoneTitle: 'الهاتف',
      socialTitle: 'السوشال ميديا',
      support: 'دعم',
      supportSub: 'نرد خلال دقائق',
      infoLocations: 'المواقع',
      infoGlobal: '+ حضور عالمي افتراضي',
      infoResponse: 'متوسط وقت الاستجابة',
      infoResponseSub: 'أقل من 5 دقائق خلال ساعات العمل',
      sendTitle: 'أرسل رسالة',
      sendSub: 'املأ النموذج وسنعاود التواصل معك.',
      phoneOptional: 'الهاتف (اختياري)',
      name: 'الاسم الكامل',
      namePlaceholder: 'اسمك',
      email: 'البريد الإلكتروني',
      emailPlaceholder: 'you@example.com',
      subject: 'الموضوع',
      subjectPlaceholder: 'عن ماذا تتحدث؟',
      message: 'الرسالة',
      messagePlaceholder: 'اكتب رسالتك هنا...',
      send: 'إرسال الرسالة',
      successTitle: 'تم إرسال الرسالة',
      successBody: 'شكراً لك! سنرد عليك خلال 24 ساعة.',
      sendAnother: 'إرسال رسالة أخرى',
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = translations[lang];

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = t.dir;
  }, [lang, t.dir]);

  const toggleLang = () => setLang((prev) => (prev === 'en' ? 'ar' : 'en'));

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t, dir: t.dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
